USE [master]
GO

/****** Object:  Database [QLTiemGiay]    Script Date: 17/08/2023 12:42:51 CH ******/
CREATE DATABASE [QLTiemGiay]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'QLTiemGiay', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.CSDLSERVER\MSSQL\DATA\QLTiemGiay.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'QLTiemGiay_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.CSDLSERVER\MSSQL\DATA\QLTiemGiay_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [QLTiemGiay].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [QLTiemGiay] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [QLTiemGiay] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [QLTiemGiay] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [QLTiemGiay] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [QLTiemGiay] SET ARITHABORT OFF 
GO

ALTER DATABASE [QLTiemGiay] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [QLTiemGiay] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [QLTiemGiay] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [QLTiemGiay] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [QLTiemGiay] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [QLTiemGiay] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [QLTiemGiay] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [QLTiemGiay] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [QLTiemGiay] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [QLTiemGiay] SET  DISABLE_BROKER 
GO

ALTER DATABASE [QLTiemGiay] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [QLTiemGiay] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [QLTiemGiay] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [QLTiemGiay] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [QLTiemGiay] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [QLTiemGiay] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [QLTiemGiay] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [QLTiemGiay] SET RECOVERY FULL 
GO

ALTER DATABASE [QLTiemGiay] SET  MULTI_USER 
GO

ALTER DATABASE [QLTiemGiay] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [QLTiemGiay] SET DB_CHAINING OFF 
GO

ALTER DATABASE [QLTiemGiay] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [QLTiemGiay] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [QLTiemGiay] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [QLTiemGiay] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO

ALTER DATABASE [QLTiemGiay] SET QUERY_STORE = ON
GO

ALTER DATABASE [QLTiemGiay] SET QUERY_STORE (OPERATION_MODE = READ_WRITE, CLEANUP_POLICY = (STALE_QUERY_THRESHOLD_DAYS = 30), DATA_FLUSH_INTERVAL_SECONDS = 900, INTERVAL_LENGTH_MINUTES = 60, MAX_STORAGE_SIZE_MB = 1000, QUERY_CAPTURE_MODE = AUTO, SIZE_BASED_CLEANUP_MODE = AUTO, MAX_PLANS_PER_QUERY = 200, WAIT_STATS_CAPTURE_MODE = ON)
GO

ALTER DATABASE [QLTiemGiay] SET  READ_WRITE 
GO


/****** Object:  Table [dbo].[tblCTHDBan]    Script Date: 17/08/2023 12:43:23 CH ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO
-- tbl Chi Tiet HD Ban
CREATE TABLE [dbo].[tblCTHDBan](
	[MaSP] [int] NOT NULL,
	[SoLuong] [int] NOT NULL,
	[GiaBan] [float] NOT NULL,
 CONSTRAINT [PK_tblCTHDBan] PRIMARY KEY CLUSTERED 
(
	[MaSP] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO

--tbl Hoa Don Ban
CREATE TABLE [dbo].[tblHDBan](
	[MaHDBan] [int] IDENTITY(1,1) NOT NULL,
	[MaNV] [int] NOT NULL,
	[MaKH] [int] NOT NULL,
	[NgayBan] [datetime] NULL,
	[TongTienBan] [float] NOT NULL,
 CONSTRAINT [PK_tblHDBan] PRIMARY KEY CLUSTERED 
(
	[MaHDBan] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO

ALTER TABLE [dbo].[tblHDBan] ADD  CONSTRAINT [DF__tblHDBan__NgayBa__76619304]  DEFAULT (sysdatetime()) FOR [NgayBan]
GO

ALTER TABLE [dbo].[tblHDBan]  WITH NOCHECK ADD  CONSTRAINT [FK_tblHDBan_tblKhachHang] FOREIGN KEY([MaKH])
REFERENCES [dbo].[tblKhachHang] ([MaKH])
GO

ALTER TABLE [dbo].[tblHDBan] CHECK CONSTRAINT [FK_tblHDBan_tblKhachHang]
GO

ALTER TABLE [dbo].[tblHDBan]  WITH NOCHECK ADD  CONSTRAINT [FK_tblHDBan_tblNhanVien] FOREIGN KEY([MaNV])
REFERENCES [dbo].[tblNhanVien] ([MaNV])
GO

ALTER TABLE [dbo].[tblHDBan] CHECK CONSTRAINT [FK_tblHDBan_tblNhanVien]
GO

--tbl Khach Hang
CREATE TABLE [dbo].[tblKhachHang](
	[MaKH] [int] IDENTITY(0,1) NOT NULL,
	[TenKH] [nvarchar](50) NOT NULL,
	[DiaChi] [nvarchar](50) NOT NULL,
	[SDT] [nvarchar](50) NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[MaKH] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO

-- tbl Nha Cung Cap
CREATE TABLE [dbo].[tblNhaCC](
	[MaNCC] [int] IDENTITY(1,1) NOT NULL,
	[TenNCC] [nvarchar](50) NOT NULL,
	[DiaChi] [nvarchar](50) NOT NULL,
	[SDT] [nvarchar](50) NOT NULL,
 CONSTRAINT [PK_tblNhaCC] PRIMARY KEY CLUSTERED 
(
	[MaNCC] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO


--tbl Nhan Vien
CREATE TABLE [dbo].[tblNhanVien](
	[MaNV] [int] IDENTITY(0,1) NOT NULL,
	[TenNV] [nvarchar](50) NOT NULL,
	[DiaChi] [nvarchar](50) NOT NULL,
	[SDT] [nvarchar](50) NOT NULL,
	[Email] [nvarchar](50) NOT NULL,
	[VaiTro] [bit] NOT NULL,
	[TrangThai] [bit] NOT NULL,
	[MK] [nvarchar](50) NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[MaNV] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO


-- tbl San Pham
CREATE TABLE [dbo].[tblSanPham](
	[MaSP] [int] IDENTITY(1,1) NOT NULL,
	[TenSP] [nvarchar](50) NOT NULL,
	[SoLuong] [int] NOT NULL,
	[GiaNhapSP] [float] NOT NULL,
	[GiaBanSP] [float] NOT NULL,
	[AnhSP] [image] NOT NULL,
	[GhiChu] [nvarchar](100) NOT NULL,
 CONSTRAINT [PK_tblSanPham] PRIMARY KEY CLUSTERED 
(
	[MaSP] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO


